#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          verticalMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// define global array variable to store the state of the board
// 6 rows, 7 columns
// values: 0 for empty, 1 for player, 2 for com
int board[6][7];
int boardMinimax[6][7];

// we don't need to differentiate between red or yellow
// because there will only be one new opponent piece every turn
#define colorMin 20

int numRobotMoves = 0;
int maxCol;

// define data structures to store the encoder values of certain positions
int sensorHorizontal[7] = {250, 356, 460, 560, 662, 765, 867};
int armHorizontal[7] = {356, 460, 560, 662, 765, 867, 970};
int sensorVertical[6] = {0, 0, 0, 0, 0, 0};
#define armTop 525

void nextTurnSound()
{
	// beep
	playTone(100,30);
	while(bSoundActive)
		sleep(1);
}

void rotateArm()
{
	// rotate arm downwards to pick up piece
	setMotorTarget(armMotor, 50, 50);
	waitUntilMotorStop(armMotor);
	delay(200);
	setMotorTarget(armMotor, 120, 100);
	waitUntilMotorStop(armMotor);
	delay(200);
	// rotate arm back up to position 0
	setMotorTarget(armMotor, 0, 10);
	waitUntilMotorStop(armMotor);
}

void senseComputerPiece()
{
	while (true)
	{
		// if computer piece is sensed
	  if (getColorReflected(S3) >= colorMin)
		{
			// move over so the arm is in position
			setMotorSyncEncoder(leftMotor, rightMotor, 0, 100, 40);
			//setMotorTarget(leftMotor, 100, 40);
			//setMotorTarget(rightMotor, 100, 40);
			waitUntilMotorStop(leftMotor);
			waitUntilMotorStop(rightMotor);
			// pick up the chip
			rotateArm();
			break;
		}
	}
}

void moveToLocation(int h, int v)
{
	// move horizontally
	setMotorSyncEncoder(leftMotor, rightMotor, 0, h, 70);
	waitUntilMotorStop(leftMotor);
	// move vertically
	setMotorTarget(verticalMotor, v, 70);
	waitUntilMotorStop(verticalMotor);
}

void playEndSound(int winner)
{
	if (winner == 1)
	{
		// play winning sound
		playSoundFile("/home/root/lms2012/prjs/rc/win2");
		sleep(2000);
	}
	else if (winner == 0){
		// play tie sound (beep 3 times)
		for (int i = 0; i < 3; i++)
		{
			playTone(100,30);
			while(bSoundActive)
				sleep(1);
			delay(300);
		}
	}
	else
	{
		// play losing sound
		playSoundFile("/home/root/lms2012/prjs/rc/lose");
		sleep(4000);
	}
}

task main()
{
	senseComputerPiece();
	moveToLocation(armHorizontal[0]-2, armTop);
	rotateArm();
}
